### ISSUE TITLE
Идея для PR: устранить дублирование CSS при использовании clearfix()

### ISSUE THREAD

**Issue by riseremi** [CSSSR/csssr-project-template#155]
Привет.

Заметил, что при использовании миксина `clearfix()` в итоговом CSS свойства дублируются для каждого использования.

``` stylus
.container
    clearfix()

.content
    clearfix()
```

Результат:

``` css
.container:after {
    display: table;
    clear: both;
    content: "";
}

.content:after {
    display: table;
    clear: both;
    content: "";
}
```

Можно переписать миксин с использованием `@extends`, чтобы всё собиралось в одно место.

``` stylus
.clearfix
    &:after
        display table
        clear both
        content ''

clearfix()
    @extends .clearfix
```

Результат:

``` css
.container:after, .content:after {
    display: table;
    clear: both;
    content: "";
}
```

Если от такого изначально отказались, было бы интересно узнать, почему.
