### ISSUE TITLE
@font-face не попадает в скомпилированый файл

### ISSUE THREAD

**Issue by jt3k** [CSSSR/csssr-project-template#156]
я добавляю такой код в `app/styles/helpers/fonts.styl`:
```css
@font-face {
	font-family: 'Officina Serif';
	src: url('../fonts/officinaserifc-book-webfont.eot');
	src: url('../fonts/officinaserifc-book-webfont.eot#iefix') format('embedded-opentype'), url('../fonts/officinaserifc-book-webfont.woff') format('woff'), url('../fonts/officinaserifc-book-webfont.ttf') format('truetype'), url('../fonts/officinaserifc-book-webfont.svg') format('svg');
	font-weight: normal;
	font-style: normal;
}
```

после компиляции я не вижу в стилях этого подключения  шрифта.

я пробовал также до @font-face и после   добавлять произвольные css-правила  и они успешно попадают в  результирующий  цсс-файл, но между ними пусто.

Любые ваши идеи приветствуются.
