### ISSUE TITLE
Добавление шрифтов в файле fonts.styl

### ISSUE THREAD

**Issue by gearmobile** [CSSSR/csssr-project-template#47]
Как правильно добавлять кастомные шрифты в файл `fonts.styl` (`app/styles/base/fonts.styl`)?

Этот файл имеет синтаксис Stylus. Допустимо ли добавлять в него custom-шрифты в CSS-синтаксисе?

Например, таким образом:

```css
/* font-family: "OswaldRegular"; */
@font-face {
  font-family: 'OswaldRegular';
  src: url('../fonts/OswaldRegular/oswald-regular-webfont.eot');
  src: url('../fonts/OswaldRegular/oswald-regular-webfont.eot?#iefix') format('embedded-opentype'),
       url('../fonts/OswaldRegular/oswald-regular-webfont.woff2') format('woff2'),
       url('../fonts/OswaldRegular/oswald-regular-webfont.woff') format('woff'),
       url('../fonts/OswaldRegular/oswald-regular-webfont.ttf') format('truetype'),
       url('../fonts/OswaldRegular/oswald-regular-webfont.svg#oswaldregular') format('svg');
  font-weight: normal;
  font-style: normal;
}
```
Или перед добавлением шрифтов нужно выполнять предварительное форматирование из формата CSS  в формат Stylus?

Или (возможно) я что-то неправильно понимаю и существует другой способ?
